[package]
name = "r-epub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.60"
zip = {version = "1.2.2", default-features = false, features = ["deflate", "deflate64"] }
